[package]
name = "vector"
version = "3.1.0"
edition = "2021"

[features]
default = ["std"]
serde = ["dep:serde"]
std = []

[dependencies]
libm = "0.2.8"
serde = { version = "1.0.219", features = ["derive"], optional = true }
